# -*- coding: utf-8 -*-
"""Projeto_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZlF8u3hRVCv3P6r52XnM1uT_CpxNwQo8
"""

cand1={}
cand2={}
cont1= 0
cont2= 0

def cadastro():
  prox = input(str("\nDeseja cadastrar um candidato?\n0 - NÃO\n1 - SIM\nOPÇÃO: "))
  
  while (prox == "1"): 
    print("\nPara qual caga gostaria de se Cadidatar \nAnalista de dados [0]  \nDesenvolvedor[1]:")
    candV = input("\nQual vaga gostaria de se candidatar:")
    if candV == "0":
      nome = input("\nDigite seu Nome:")
      resumo = input("\nEscreva um resumo das suas experiencias:")
      cand1.update({nome:resumo})
    
      prox = input("\nDeseja continuar com o cadastro?\n0 - NÃO\n1 - SIM\nOPÇÃO:")
    elif candV == "1":
      nome = input("\nDigite seu Nome:")
      resumo = input("\nEscreva um resumo das suas experiencias")
      cand2.update({nome:resumo})
      prox = input("\nDeseja continuar com o cadastro?\n0 - NÃO\n1 - SIM\nOPÇÃO:")
    if prox == "0":
      break

def localizar(cand1,cand2):
  global cont1,cont2
  for aprov in cand2.values():
    if 'Python'or 'Programação'or 'Desenvolvimento' or 'python' or 'programação' or 'desenvolvimento' in aprov:
      cont1 = cont1+1
    
  for aprov in cand1.values():
    if 'Análise de dados'or 'Dados'or 'SQL'or 'análise de dados'or 'dados'or 'sql' in aprov:
          cont2 =cont2+1


  print(cand1)
  print(cand2)

  print("A quantidade de pessoas que se cadastraram para vaga de desenvolvedor é {}".format(len(cand1)))
  print("A quantidade de pessoas que se cadastraram para vaga de Analista é {}".format(len(cand2)))
  print("o numero de candidatos aptos para a vaga é {}".format(cont1))
  print("o numero de candidatos aptos para a vaga é {}".format(cont2))
cadastro()
localizar(cand1,cand2)

